In [7]:
# importing of modules

import numpy as np     # for math functions
import pandas as pd    # for importing and using datasets
import random          # for generating random weights

In [8]:
# loading of data

def load_data(filename, target):
    dataset = pd.read_csv("dataset/"+filename, sep="\t")  # read .csv file into dataset variable

    print(dataset,"\n")

    x = np.array(dataset.drop([target],1)) # x contains all the features. Does not include target
    y = np.array(dataset[target]) # y contains the target class 

    print("\nX = \n",x)
    print("\nY = \n",y)

    print("\n\n")
    
    return (dataset,x,y,target)

inp = load_data("diagnosis-data.csv","decision")

    temperature  nausea  lumbarpain  urinepushing  pains  burning  \
0          35,5       0           1             0      0        0   
1          35,9       0           0             1      1        1   
2          35,9       0           1             0      0        0   
3          36,0       0           0             1      1        1   
4          36,0       0           1             0      0        0   
..          ...     ...         ...           ...    ...      ...   
115        41,4       0           1             1      0        1   
116        41,5       0           0             0      0        0   
117        41,5       1           1             0      1        0   
118        41,5       0           1             1      0        1   
119        41,5       0           1             1      0        1   

     inflamation  decision  
0              0         0  
1              1         0  
2              0         0  
3              1         0  
4              0         0

In [9]:
"""
def add_initial_column(x,val):
    m = len(x)

    initial_column = np.array([val for i in range(m)])
    x = np.column_stack((initial_column, x))   
    
    return x
"""
# x_data = add_initial_column(inp[1],-1)
x_data = np.array(inp[1])
y_data = np.array([inp[2]])
y_data = np.transpose(y_data)
x_data = x_data[:,1:]
print(x_data,"\n")
print(y_data)

[[0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 1 1 1 1]
 [0 0 1 1 1 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 1 1 1 1]
 [0 0 1 1 1 1]
 [0 1 0 0 0 0]
 [0 0 1 1 0 1]
 [0 0 1 1 0 1]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 1 1 1 1]
 [0 0 1 1 1 1]
 [0 0 1 1 1 1]
 [0 0 1 0 0 1]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 1 0 0 1]
 [0 0 1 1 0 1]
 [0 1 0 0 0 0]
 [0 0 1 0 0 1]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 1 0 0 1]
 [0 1 0 0 0 0]
 [0 0 1 0 0 1]
 [0 0 1 1 0 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 1 0 0 1]
 [0 0 1 0 0 1]
 [0 0 1 1 0 1]
 [0 0 1 1 0 1]
 [0 0 1 1 1 1]
 [0 0 1 1 0 1]
 [0 0 1 1 0 1]
 [0 1 0 0 0 0]
 [0 0 1 0 0 1]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 1 0 0 1]
 [0 0 1 1 0 1]
 [0 0 1 1 0 1]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 1 0 0 1]
 [0 1 1 0 1 0]
 [0 1 1 0 1 0]
 [0 1 1 0 1 0]
 [0 1 1 0 1 0]
 [0 1 1 0 1 0]
 [0 1 1 0 1 0]
 [0 1 1 0 

In [25]:
def activation_func(x):
    return sigmoid(x)


def sigmoid(x):
    # print("Exp: ", np.exp(-x))
    x = np.array(x, dtype=int)
    return 1/(1 + x)

def sign(x):
    res = 0 if x <= 0 else 1
    # print(res)
    return res


In [26]:
def sigmoid_deriv(x):
    x = np.array(x, dtype=int)
    return x * ( 1 - x)

In [44]:
class MLP_single_hidden():
    
    def __init__(self, numI, numH, numO, x_data, y_data):
        self.numI = numI
        self.numH = numH
        self.numO = numO
        self.x = x_data
        self.y = y_data
        self.epochs = 5000
        self.lr = 0.1
        self.tp = 0
        self.tn = 0
        self.fp = 0
        self.fn = 0
        self.cost_array = []
        self.initialize_weights()
        self.initialize_bias()
        
    def initialize_weights(self):
        self.hiddenW = np.random.uniform(size=(self.numI, self.numH))
        self.outputW = np.random.uniform(size=(self.numH, self.numO))

    def initialize_bias(self):
        self.hiddenB = np.random.uniform(size=(1,self.numH))
        self.outputB = np.random.uniform(size=(1,self.numO))
        
    def forward_propagation(self):
        self.hidden_layer_activation = np.dot(self.x, self.hiddenW)
        self.hidden_layer_activation += self.hiddenB
        self.hidden_layer_output = sigmoid(self.hidden_layer_activation)

        self.output_layer_activation = np.dot(self.hidden_layer_output, self.outputW)
        self.output_layer_activation += self.outputB
        self.y_predict = sigmoid(self.output_layer_activation)
        
    def backward_propagation(self):
        self.error = ((self.y - self.y_predict)) #**2).mean()
        self.d_y_predict = self.error * sigmoid_deriv(self.y_predict)

        self.error_hidden_layer = self.d_y_predict.dot(self.outputW.T)
        self.d_hidden_layer = self.error_hidden_layer * sigmoid_deriv(self.hidden_layer_output)
        
    def update_weights(self):
        #print((self.hidden_layer_output.T.dot(self.d_y_predict))* self.lr)
        #print((self.outputW))
        #print((self.outputW)+((self.hidden_layer_output.T.dot(self.d_y_predict))* self.lr))
        self.outputW = (self.outputW)+((self.hidden_layer_output.T.dot(self.d_y_predict))* self.lr)
        #self.outputW += self.hidden_layer_output.T.dot(self.d_y_predict) * self.lr
        #print("hi",(self.x.T.dot(self.d_hidden_layer)) * self.lr)
        #print(self.hiddenW)
        #print(self.hiddenW + (self.x.T.dot(self.d_hidden_layer)) * self.lr )
        self.hiddenW = (self.hiddenW + (self.x.T.dot(self.d_hidden_layer)) * self.lr )
        
    def update_bias(self):
        self.outputB = self.outputB + (np.sum(self.d_y_predict, axis=0, keepdims=True) * self.lr)
        self.hiddenB = self.hiddenB + (np.sum(self.d_hidden_layer, axis=0, keepdims=True) * self.lr)
        
    def train(self):
        temp_error = 100000
        for i in range(self.epochs):
            self.forward_propagation()
            self.backward_propagation()
            self.update_weights()
            self.update_bias()
            self.cost_array.append(self.error)
            
            
    def print_weights(self):
        print("HiddenW: ",end="")
        print(*self.hiddenW)
        print("OutputW: ",end="")
        print(*self.outputW)
        
    def print_bias(self):
        print("HiddenB: ",end="")
        print(*self.hiddenB)
        print("OutputB: ",end="")
        print(*self.outputB)
        
    def print_y_predict(self):
        print("\n\nPredicted Value of Y: ", end="")
        print(*self.y_predict)
        print("Expected Value of Y:  ", end="")
        print(*self.y)
        
        for i in self.y_predict:
            for j in self.y:
                if i==1 and j==1:
                    self.tp += 1
                elif i == 0 and j == 0:
                    self.tn += 1
                elif i == 1 and  j == 0:
                    self.fp += 1
                else:
                    self.fn += 1
        
        print("Accuracy = ",((self.tp+self.tn)/(self.tp+self.tn+self.fp+self.fn))*100,"%")
        print("Recall = ",(self.tp)/(self.tp+self.fn))
        print("Precision = ",(self.tp)/(self.tp+self.fp))
        
        
    def apply_threshold(self):
        for i in range(self.y_predict.size):
            if self.y_predict[i][0]  < 0.5:
                self.y_predict[i][0] = 0
            else:
                self.y_predict[i][0] = 1
            

In [54]:
XOR = MLP_single_hidden(6,7,1,x_data,y_data)

print("Initial: ")
XOR.print_weights()
XOR.print_bias()

XOR.train()

print("\nFinal: ")
XOR.print_weights()
XOR.print_bias()
XOR.apply_threshold()
XOR.print_y_predict()

Initial: 
HiddenW: [0.77485452 0.48318794 0.25928727 0.75606827 0.19434691 0.15329421
 0.09533022] [0.71009305 0.62694465 0.38466284 0.10892284 0.34659509 0.7713332
 0.19528608] [0.34327853 0.23023833 0.36228844 0.60824239 0.28400572 0.86432676
 0.6521719 ] [0.07504234 0.47541461 0.02053135 0.97259419 0.10324775 0.89916351
 0.71544399] [0.03885334 0.52960518 0.70872282 0.56450133 0.14552036 0.94048138
 0.22739679] [0.0662932  0.21568566 0.04222909 0.76959101 0.29357105 0.61226887
 0.38721252]
OutputW: [0.28723909] [0.98611236] [0.54156018] [0.07548183] [0.90794135] [0.34944011] [0.40510753]
HiddenB: [0.72550743 0.17390327 0.27728418 0.98313649 0.46126799 0.37607223
 0.05851534]
OutputB: [0.26076573]

Final: 
HiddenW: [0.7748545225654011 0.48318793918134073 0.2592872741212313
 0.7560682657964832 0.19434691403192594 0.15329421338135496
 0.09533021558880961] [0.7100930519002607 0.6269446484655398 0.3846628406126398
 0.10892284178806733 0.3465950895792812 0.7713332017694066
 0.195286083373