Trying out Decision Trees with Scikit, Script-Score 0.84100

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import tree


import os
print(os.listdir("/content/drive/MyDrive"))

# Any results you write to the current directory are saved as output.


df_train = pd.read_csv("/content/drive/MyDrive/mnist_train.csv")
df_test = pd.read_csv("/content/drive/MyDrive/mnist_test.csv")

print(df_train.shape)
print(df_test.shape)

['JavaScript and JQuery Interactive Front-End Web Development.pdf', 'A1 Goethe Prüfung', 'MARKETING MANIAQUESTIONS.gdoc', 'Maths', 'hangmancpp.gdoc', 'Colab Notebooks', 'Assessment v1', 'GuviCertification - 9fZ5458a2N1n1T2757 machinelearning.pdf', 'GuviCertification - 22M78537513cQ1S947python.pdf', 'WORDITOUT.gdoc', 'Screenshot_2020-02-18-21-52-45-266_com.google.android.apps.photos.jpg', 'srihari.pdf', 'srihari_resume (1).pdf', 'pass.jpg', 'ANDREW_NG_ML.zip', 'sem3.zip', 'Song1.zip', 'SRFP-Four-week report-2020.pdf', 'SRFP-Four-week report-2020.gdoc', 'srihariresume (1).pdf', 'IASC-COMPLETION', 'CitiInterns - CEG-CSE2020.gsheet', 'resume.pdf', 'srihariresume.pdf', 'Internship-Preparations', 'online_certificates', 'SUMMER-VACATION2020', 'srihari.jpg', 'Untitled form.gform', 'Untitled form (Responses).gsheet', 'research-paper.gdoc', 'OpenCV_AlgorithmUnlock.zip', 'srihari.zip', 'srihari_resume.pdf', 'CIP_Project_Retry', 'CIP_Project', '.ipynb_checkpoints', 'Sherlock Holmes ACM Techfiesta

In [ ]:
df_train.head()

label  1x1  1x2  1x3  1x4  1x5  ...  28x23  28x24  28x25  28x26  28x27  28x28
0      5    0    0    0    0    0  ...      0      0      0      0      0      0
1      0    0    0    0    0    0  ...      0      0      0      0      0      0
2      4    0    0    0    0    0  ...      0      0      0      0      0      0
3      1    0    0    0    0    0  ...      0      0      0      0      0      0
4      9    0    0    0    0    0  ...      0      0      0      0      0      0

[5 rows x 785 columns]

In [ ]:
X = []
y = []
for row in df_train.iterrows() :
    label = row[1][0] # label (the number visible in the image)
    image = list(row[1][1:]) # image information as list, without label
    image = np.array(image) / 255
    X.append(image)
    y.append(label)

X = np.array(X)
y = np.array(y)
print(len(X))
print(len(y))

60000
60000


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
print(len(X_train), len(y_train))
print(X_train[1].shape)

45000 45000
(784,)


In [ ]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_predt = clf.predict(X_train)
print(y_predt[0:20], ".....")
print(y_train[0:20], ".....")
print("Accuracy = ",metrics.accuracy_score(y_train, y_predt)*100)

[0 1 1 9 0 2 1 8 7 7 8 6 1 5 0 9 2 3 6 7] .....
[0 1 1 9 0 2 1 8 7 7 8 6 1 5 0 9 2 3 6 7] .....
Accuracy =  100.0


In [ ]:
confusion = metrics.confusion_matrix(y_true = y_train, y_pred = y_predt)
confusion

array([[4428,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 5093,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 4487,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 4613,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0, 4399,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 4038,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0, 4436,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 4630,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 4406,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 4470]])

In [ ]:
class_wise = metrics.classification_report(y_true = y_train, y_pred = y_predt)
print(class_wise)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4428
           1       1.00      1.00      1.00      5093
           2       1.00      1.00      1.00      4487
           3       1.00      1.00      1.00      4613
           4       1.00      1.00      1.00      4399
           5       1.00      1.00      1.00      4038
           6       1.00      1.00      1.00      4436
           7       1.00      1.00      1.00      4630
           8       1.00      1.00      1.00      4406
           9       1.00      1.00      1.00      4470

    accuracy                           1.00     45000
   macro avg       1.00      1.00      1.00     45000
weighted avg       1.00      1.00      1.00     45000



In [ ]:
clf

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
clf.criterion = 'entropy'

In [ ]:
clf
clf.max_depth = 10
clf = clf.fit(X_train, y_train)
y_predt = clf.predict(X_train)
print(y_predt[0:20], ".....")
print(y_train[0:20], ".....")
print("Accuracy = ",metrics.accuracy_score(y_train, y_predt)*100)

[0 1 1 9 0 2 1 8 7 2 8 6 3 5 0 9 3 3 6 7] .....
[0 1 1 9 0 2 1 8 7 7 8 6 1 5 0 9 2 3 6 7] .....
Accuracy =  92.2


In [ ]:
confusion = metrics.confusion_matrix(y_true = y_train, y_pred = y_predt)
confusion

array([[4305,    2,   15,    9,    8,   28,   18,    9,   26,    8],
       [   1, 4952,   33,   19,    6,   13,    8,   20,   33,    8],
       [  34,   18, 4106,   61,   46,   28,   35,   68,   74,   17],
       [  17,   19,   61, 4084,   13,  189,    6,   66,   74,   84],
       [   9,   25,   30,   14, 3926,   11,   25,   36,   48,  275],
       [  40,   21,   16,   98,   24, 3697,   25,   11,   45,   61],
       [  35,   33,   28,   14,   51,   61, 4152,    5,   53,    4],
       [   4,   14,   60,   27,   40,    8,    2, 4290,   33,  152],
       [  27,   54,   54,   52,   26,   53,   38,   24, 3982,   96],
       [  14,   13,   19,   69,  147,   72,    1,   73,   66, 3996]])

In [ ]:
class_wise = metrics.classification_report(y_true=y_train, y_pred=y_predt)
print(class_wise)

              precision    recall  f1-score   support

           0       0.96      0.97      0.97      4428
           1       0.96      0.97      0.97      5093
           2       0.93      0.92      0.92      4487
           3       0.92      0.89      0.90      4613
           4       0.92      0.89      0.90      4399
           5       0.89      0.92      0.90      4038
           6       0.96      0.94      0.95      4436
           7       0.93      0.93      0.93      4630
           8       0.90      0.90      0.90      4406
           9       0.85      0.89      0.87      4470

    accuracy                           0.92     45000
   macro avg       0.92      0.92      0.92     45000
weighted avg       0.92      0.92      0.92     45000



In [ ]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(y_pred[0:20], ".....")
print(y_test[0:20], ".....")
print(metrics.accuracy_score(y_test, y_pred))

[7 3 8 9 3 9 7 7 5 4 2 5 6 9 1 7 4 2 0 7] .....
[7 3 8 9 3 9 7 7 5 4 2 5 6 8 1 7 4 8 0 7] .....
0.860909090909091


In [ ]:
clf.criterion = 'entropy'
clf.max_depth = 21
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(y_pred[0:20], ".....")
print(y_test[0:20], ".....")
print(metrics.accuracy_score(y_test, y_pred))

[7 3 8 9 3 9 7 7 5 4 6 5 6 8 1 7 4 7 0 0] .....
[7 3 8 9 3 9 7 7 5 4 2 5 6 8 1 7 4 8 0 7] .....
0.8677777777777778


In [ ]:
clf = tree.DecisionTreeClassifier()
clf.criterion = 'entropy'
clf.splitter = 'best'
clf.max_depth = 13
clf = clf.fit(X_train, y_train)
y_predtt = clf.predict(X_test)
print(y_predtt[0:20], ".....")
print(y_test[0:20], ".....")
print("Accuracy = ",metrics.accuracy_score(y_test, y_predtt)*100)

[7 3 8 9 3 9 7 7 5 4 4 5 6 9 1 7 4 8 0 7] .....
[7 3 8 9 3 9 7 7 5 4 2 5 6 8 1 7 4 8 0 7] .....
Accuracy =  87.11333333333333


In [ ]:
confusion = metrics.confusion_matrix(y_true = y_test, y_pred = y_predtt)
confusion

array([[1377,    0,   17,    9,    8,   18,   35,    5,   20,    6],
       [   1, 1598,    7,   13,    6,    7,    5,    4,    7,    1],
       [  18,   18, 1224,   35,   20,   15,   32,   45,   50,   14],
       [  10,   12,   43, 1262,   16,   71,   14,   25,   36,   29],
       [   9,    5,    9,   10, 1257,   10,   26,   22,   19,   76],
       [  23,    8,   17,   57,   14, 1155,   33,   10,   38,   28],
       [  16,    3,   32,   10,   17,   27, 1342,    4,   28,    3],
       [   6,   20,   47,   15,   20,    4,    2, 1482,    9,   30],
       [  23,   29,   45,   52,   33,   39,   27,   12, 1155,   30],
       [  12,    7,   17,   43,   89,   20,   13,   33,   30, 1215]])

In [ ]:
class_wise = metrics.classification_report(y_true=y_test, y_pred=y_predtt)
print(class_wise)

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      1495
           1       0.94      0.97      0.95      1649
           2       0.84      0.83      0.84      1471
           3       0.84      0.83      0.83      1518
           4       0.85      0.87      0.86      1443
           5       0.85      0.84      0.84      1383
           6       0.88      0.91      0.89      1482
           7       0.90      0.91      0.90      1635
           8       0.83      0.80      0.81      1445
           9       0.85      0.82      0.83      1479

    accuracy                           0.87     15000
   macro avg       0.87      0.87      0.87     15000
weighted avg       0.87      0.87      0.87     15000



In [ ]:
clf.criterion = 'gini'
clf.splitter = 'random'
clf.max_depth = 18
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(y_pred[0:20], ".....")
print(y_test[0:20], ".....")
print(metrics.accuracy_score(y_test, y_pred))

[7 3 8 9 3 9 7 7 5 4 8 5 6 4 1 9 4 9 0 7] .....
[7 3 8 9 3 9 7 7 5 4 2 5 6 8 1 7 4 8 0 7] .....
0.8646464646464647


In [ ]:
clf.criterion = 'gini'
clf.splitter = 'best'
clf.max_depth = 18
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(y_pred[0:20], ".....")
print(y_test[0:20], ".....")
print(metrics.accuracy_score(y_test, y_pred))

[7 3 8 9 3 9 7 7 5 4 2 5 8 9 1 7 4 2 0 7] .....
[7 3 8 9 3 9 7 7 5 4 2 5 6 8 1 7 4 8 0 7] .....
0.8652020202020202
